### ISSUE TITLE
npm - Angular 2 can't find Promise,Map,Set and Iterator

### ISSUE THREAD

**Issue by DoomerDGR8** [mithunvp/ng2Mvc5Demo#1]
After cloning the latest, I updated the regular NuGets and tried to build website

![image](https://cloud.githubusercontent.com/assets/825078/17552539/89240310-5f11-11e6-9be0-b3802d76fe88.png)

**Comment by DoomerDGR8** [comment]
Default task:

`D:\Projects\Repos\ng2Mvc5Demo\ng2Mvc5Demo> cmd.exe /c gulp -b "D:\Projects\Repos\ng2Mvc5Demo\ng2Mvc5Demo" --color --gulpfile "D:\Projects\Repos\ng2Mvc5Demo\ng2Mvc5Demo\Gulpfile.js" default
[15:47:56] Using gulpfile D:\Projects\Repos\ng2Mvc5Demo\ng2Mvc5Demo\Gulpfile.js
[15:47:56] Starting 'scriptsNStyles'...
[15:47:56] Finished 'scriptsNStyles' after 14 ms
[15:47:56] Starting 'ts'...
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/application_ref.d.ts(79,88): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/application_ref.d.ts(137,42): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/application_ref.d.ts(196,33): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/di/reflective_provider.d.ts(115,123): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/di/reflective_provider.d.ts(115,165): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/lang.d.ts(68,59): error TS2304: Cannot find name 'Map'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(9,14): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(15,32): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(16,38): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(17,35): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(17,93): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(18,34): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(18,50): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(19,32): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(19,149): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/facade/promise.d.ts(20,43): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/compiler.d.ts(13,59): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/component_resolver.d.ts(9,58): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/component_resolver.d.ts(13,49): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(61,148): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(102,144): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(107,139): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(108,135): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(18,53): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(26,53): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/platform-browser-dynamic/index.d.ts(81,90): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/platform-browser-dynamic/index.d.ts(85,99): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/@angular/platform-browser-dynamic/index.d.ts(89,99): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.
tsScripts\boot.ts(1,1): error TS6053: File 'D:/Projects/Repos/ng2Mvc5Demo/ng2Mvc5Demo/typings/globals/core-js/index.d.ts' not found.
[15:48:02] TypeScript: 51 semantic errors
[15:48:02] TypeScript: emit failed
[15:48:02] Finished 'ts' after 6.92 s
[15:48:02] Starting 'watch.ts'...
[15:48:02] Finished 'watch.ts' after 9.64 ms
[15:48:02] Starting 'watch'...
[15:48:02] Finished 'watch' after 2.37 μs
[15:48:02] Starting 'default'...
[15:48:02] Finished 'default' after 1.58 μs`

**Comment by mithunvp** [comment]
Few reasons might be
1. Run 'npm install' using CMD admin rights. Recommend.
2. Update TypeScript to 1.8.\* version, I have not tested with TypeScript 2.0
3. Check how your Visual Studio is configured for GULP, TypeScript.

**Comment by OrangeInnovations** [comment]
download and follow the steps. it does not work. npm install has issues. Maybe version issue since angular 2 official release.

**Comment by mithunvp** [comment]
Updated the source code with Angular 2 Final release, it will run smoothly. TypeScript 2 RC must install. Will add Angular 2 Material later

**Comment by gberger101** [comment]
Just installed it.  As of 1/2/2017 it is am excellent and perfectly working example.  Thanks.

Need to stress to follow the README instructions.
