### ISSUE TITLE
Cannot find type definition for node

### ISSUE THREAD

**Issue by lemunk** [mithunvp/ng2Mvc5Demo#7]
Followed the readme instructions exactly. get error on running gulpfile, check vs error log and found "Cannot find type definition for node".

![capture](https://cloud.githubusercontent.com/assets/10669276/24557474/b350abe0-162f-11e7-8dd1-186c97eac1dc.PNG)

**Comment by mithunvp** [comment]
please check if typings folder is ccreated with globals\core-js folder inside it. If not then again run **typings install** from cmd

**Comment by lemunk** [comment]
I removed the reference to noide in typings inisde the ts config, seems to build and run with no errors, although i suspect this will cause issues down the line?  is this a fix or will i need to find another way like you suggested?

**Comment by mithunvp** [comment]
removing it from tsconfig file also works well, nothing to worry on that.

**Comment by lemunk** [comment]
Great stuff, thanks for the help, also great tutorial and up to date to! will definitely recommend!

**Comment by kballinas** [comment]
I had the same issue; I added @types/node to package.json - seems to work fine.

**Comment by kotpal** [comment]
Nothing works. Can the project and files be updated so that this works with Angular (latest version - which is 4)?

**Comment by mithunvp** [comment]
Updated with Angular 4.1, TypeScript 2.3... check out and plz revert.

**Comment by kotpal** [comment]
Thank you @mithunvp. The project is building now in VS2015 and I am able to run the web app as well. I will tweet about this project since I didn't find anything other than your project (so far) that shows how to build an ASP.NET MVC application with Angular 4 and TypeScript. 

Keep up the good work :)

**Comment by mithunvp** [comment]
Thanks !! spread the word 👍
