### ISSUE TITLE
Not working with Typescript 2.4.x

### ISSUE THREAD

**Issue by epot** [mithunvp/ng2Mvc5Demo#9]
I am getting a: Class 'Subject<T>' incorrectly extends base class 'Observable<T
Typescript 2.4 is taken by default if you run a fresh new npm install.

**Comment by mithunvp** [comment]
I need to check TS 2.4 version, will let you know on this.

**Comment by BartD95** [comment]
You have to update rxjs also if you want to use TS 2.4. Version 5.4.2 of rxjs worked for me with TS 2.4.

**Comment by mithunvp** [comment]
@BartD95 thanks for your info !!
